### ISSUE TITLE
Render?

### ISSUE THREAD

**Issue by DemonnoLex** [Ladysnake/RATs-Mischief#142]
Dunno if it's this mod or one of my other mods, but when I try to open that mods UI I got this crash report

---- Minecraft Crash Report ----
--
4203 | // There are four lights!
4204 |  
4205 | Time: 2023-12-30 13:35:49
4206 | Description: Rendering item
4207 |  
4208 | java.lang.NullPointerException: Cannot load from object array because "ladysnake.ratsmischief.client.render.entity.PartyHatFeatureRenderer.TEXTURES" is null
4209 | at ladysnake.ratsmischief.client.render.item.RatItemRenderer.render(RatItemRenderer.java:74)
4210 | at ladysnake.ratsmischief.client.render.item.RatItemRenderer.render(RatItemRenderer.java:21)
4211 | at software.bernie.geckolib3.renderers.geo.GeoItemRenderer.render(GeoItemRenderer.java:123)
4212 | at net.minecraft.class_756.handler$eef000$quilted_fabric_rendering_v1$fabric_onRender(class_756.java:1042)
4213 | at net.minecraft.class_756.method_3166(class_756.java)
4214 | at net.minecraft.class_918.method_23179(class_918.java:133)
4215 | at net.minecraft.class_918.method_4021(class_918.java:307)
4216 | at net.minecraft.class_918.method_4026(class_918.java:350)
4217 | at net.minecraft.class_918.method_36543(class_918.java:340)
4218 | at net.minecraft.class_918.method_27951(class_918.java:336)
4219 | at net.minecraft.class_465.method_2385(class_465.java:264)
4220 | at net.minecraft.class_465.method_25394(class_465.java:122)
4221 | at com.tiviacz.travelersbackpack.client.screen.TravelersBackpackHandledScreen.method_25394(TravelersBackpackHandledScreen.java:162)
4222 | at net.minecraft.class_757.method_3192(class_757.java:881)
4223 | at net.minecraft.class_310.method_1523(class_310.java:1177)
4224 | at net.minecraft.class_310.method_1514(class_310.java:768)
4225 | at net.minecraft.client.main.Main.method_44604(Main.java:244)
4226 | at net.minecraft.client.main.Main.main(Main.java:51)
4227 | at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
4228 | at java.base/java.lang.reflect.Method.invoke(Method.java:578)
4229 | at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551)
4230 | at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
4231 | at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
4232 | at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
4233 | at java.base/java.lang.reflect.Method.invoke(Method.java:578)
4234 | at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
4235 | at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
4236 | at org.multimc.EntryPoint.listen(EntryPoint.java:143)
4237 | at org.multimc.EntryPoint.main(EntryPoint.java:34)

</body>
</html>

**Comment by Xiribidus** [comment]
Seems like a duplicate of #141
