### ISSUE TITLE
New Rats update breaks game

### ISSUE THREAD

**Issue by red2blue** [Ladysnake/Rats-Mischief#51]
Love the update, however, looks like it isn't working

 

[11:16:03] [Render thread/ERROR]: There was a problem reading power file ratsmischief:ratified (skipping): Power type "requiem:soul_type" is not defined.
[11:16:03] [Render thread/ERROR]: Origin "ratsmischief:rat" contained unregistered power: "ratsmischief:ratified"

 

and because you added the requiem thing, I now cannot start a world due to it trying to load stuff from requiem, which I don't use.

 

 

 

[11:16:03] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load

```java.util.concurrent.ExecutionException: io.github.apace100.calio.data.DataException: Error reading data field at condition: EntityCondition json type "requiem:start_remnant_gamerule" is not defined.
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61) ~[?:?]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2069) ~[?:?]
	at net.minecraft.client.MinecraftClient.createIntegratedResourceManager(MinecraftClient:2153) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1999) ~[?:?]
	at net.minecraft.client.MinecraftClient.createWorld(MinecraftClient:1943) ~[?:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.createLevel(CreateWorldScreen:279) ~[?:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.method_19922(CreateWorldScreen:215) ~[?:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:40) ~[?:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16) ~[?:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:121) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:94) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:490) ~[?:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94) ~[?:?]
	at net.minecraft.client.Mouse.method_22686(Mouse:165) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101) ~[?:?]
	at net.minecraft.client.Mouse.method_22684(Mouse:165) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:172) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.client.util.Window.swapBuffers(Window:310) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1137) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:217) [intermediary-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.7.jar:?]
Caused by: io.github.apace100.calio.data.DataException: Error reading data field at condition: EntityCondition json type "requiem:start_remnant_gamerule" is not defined.
	at io.github.apace100.calio.data.SerializableData.lambda$read$2(SerializableData.java:91) ~[309eaadc-621b-4cbc-8501-83cede87f4fe.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:723) ~[?:?]
	at io.github.apace100.calio.data.SerializableData.read(SerializableData.java:77) ~[309eaadc-621b-4cbc-8501-83cede87f4fe.jar:?]
	at io.github.apace100.origins.origin.OriginLayer$ConditionedOrigin.read(OriginLayer.java:328) ~[Origins-1.17-1.1.4.jar:?]
	at io.github.apace100.origins.origin.OriginLayer.lambda$merge$12(OriginLayer.java:133) ~[Origins-1.17-1.1.4.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at io.github.apace100.origins.origin.OriginLayer.merge(OriginLayer.java:133) ~[Origins-1.17-1.1.4.jar:?]
	at io.github.apace100.origins.origin.OriginLayers.apply(OriginLayers.java:67) ~[Origins-1.17-1.1.4.jar:?]
	at io.github.apace100.origins.origin.OriginLayers.apply(OriginLayers.java:19) ~[Origins-1.17-1.1.4.jar:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader:13) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:134) ~[?:?]
	at net.minecraft.client.MinecraftClient.createIntegratedResourceManager(MinecraftClient:2152) ~[?:?]
	... 29 more```

**Comment by praus1** [comment]
Same issue here. I had to downgrade back to 1.2.3 again.
