### ISSUE TITLE
[Rats Mischief 1.3.5 - Fabric 1.18.1] Mod crashes game on launch

### ISSUE THREAD

**Issue by Feelzor** [Ladysnake/Rats-Mischief#80]
Using ratsmischief-1.3.5.jar, fabric-api-0.46.6+1.18.jar and geckolib-fabric-1.18-3.0.33.jar for Fabric 0.13.3 (1.18.1), the game crashes on launch.

I've made a custom modpack with Curseforge, no idea if all mods' versions are correct, but the game launched just fine without the mod.

Error is 
```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'ratsmischief'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of ladysnake.ratsmischief.client.model.RatEntityModel failed
	at ladysnake.ratsmischief.client.MischiefClient.onInitializeClient(MischiefClient.java:13)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
```

Here is the full crash report :)
[crash-2022-04-07_22.47.08-client.txt](https://github.com/Ladysnake/Rats-Mischief/files/8446414/crash-2022-04-07_22.47.08-client.txt)

**Comment by Arathain** [comment]
This is a conflict issue with Haema. Try updating both mods to their latest versions & see if the issue persists.

**Comment by FeelZoR** [comment]
Oh alright, I might have to choose between both mods then (I am using latest 1.18.1 versions, and Haema isn't working on Fabric 1.18.2).
