### ISSUE TITLE
Cannot load world with origins installed 1.18.2

### ISSUE THREAD

**Issue by Monozari** [Ladysnake/Rats-Mischief#82]
Trying to create or load a world with both rats mischief 1.3.6 and the latest origins 1.18.2 installed does not work, instead you get 
"Errors in currently selected datapacks prevented world from loading. You can either try to load it with only the vanilla datapack ("safe mode") or go to the title screen and fix it manually."

**Comment by itsdinkd** [comment]
[21:27:37] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: io.github.apace100.calio.data.DataException: Error reading data field at condition: EntityCondition json type "ratsmischief:enable_rat" is not defined.
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.client.MinecraftClient.createSaveLoader(MinecraftClient:2124) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1972) ~[?:?]
	at net.minecraft.client.MinecraftClient.createWorld(MinecraftClient:1941) ~[?:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.createLevel(CreateWorldScreen:286) ~[?:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.method_19922(CreateWorldScreen:230) ~[?:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:40) ~[?:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16) ~[?:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:121) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:94) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:492) ~[?:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94) ~[?:?]
	at net.minecraft.client.Mouse.method_22686(Mouse:165) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103) ~[?:?]
	at net.minecraft.client.Mouse.method_22684(Mouse:165) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:204) ~[client-intermediary.jar:?]
	at net.minecraft.client.util.Window.swapBuffers(Window:310) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1147) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) [fabric-loader-0.14.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.2.jar:?]
Caused by: io.github.apace100.calio.data.DataException: Error reading data field at condition: EntityCondition json type "ratsmischief:enable_rat" is not defined.
	at io.github.apace100.calio.data.SerializableData.lambda$read$2(SerializableData.java:91) ~[calio-1.5.1-b931361602e62ea4.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at io.github.apace100.calio.data.SerializableData.read(SerializableData.java:77) ~[calio-1.5.1-b931361602e62ea4.jar:?]
	at io.github.apace100.origins.origin.OriginLayer$ConditionedOrigin.read(OriginLayer.java:381) ~[Origins-1.18.2-1.4.1.jar:?]
	at io.github.apace100.origins.origin.OriginLayer.lambda$merge$12(OriginLayer.java:159) ~[Origins-1.18.2-1.4.1.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at io.github.apace100.origins.origin.OriginLayer.merge(OriginLayer.java:159) ~[Origins-1.18.2-1.4.1.jar:?]
	at io.github.apace100.origins.origin.OriginLayers.apply(OriginLayers.java:67) ~[Origins-1.18.2-1.4.1.jar:?]
	at io.github.apace100.origins.origin.OriginLayers.apply(OriginLayers.java:19) ~[Origins-1.18.2-1.4.1.jar:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader:13) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:69) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:140) ~[?:?]
	at net.minecraft.client.MinecraftClient.createSaveLoader(MinecraftClient:2123) ~[?:?]
	... 29 more

**Comment by itsdinkd** [comment]
This is the error
