### ISSUE TITLE
source of incompatibility problem (maybe) found

### ISSUE THREAD

**Issue by Monozari** [Ladysnake/Rats-Mischief#83]
Some people over at the origins discord took a look at what might be causing the issue, and they said that rat's mischief is attempting to use the ratsmischief:enable_rat tag while the tag doesn't exist in version 1.3.6 of the mod.

**Comment by GalacticRuler** [comment]
[01:45:31] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: io.github.apace100.calio.data.DataException: Error reading data field at condition: EntityCondition json type "ratsmischief:enable_rat" is not defined.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.class_310.method_40183(class_310.java:2124) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_29610(class_310.java:1972) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_29607(class_310.java:1941) ~[client-intermediary.jar:?]
	at net.minecraft.class_525.method_2736(class_525.java:286) ~[client-intermediary.jar:?]
	at net.minecraft.class_525.method_19922(class_525.java:230) ~[client-intermediary.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:40) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:121) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:492) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:103) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1150) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
Caused by: io.github.apace100.calio.data.DataException: Error reading data field at condition: EntityCondition json type "ratsmischief:enable_rat" is not defined.
	at io.github.apace100.calio.data.SerializableData.lambda$read$2(SerializableData.java:91) ~[calio-1.5.1-b931361602e62ea4.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at io.github.apace100.calio.data.SerializableData.read(SerializableData.java:77) ~[calio-1.5.1-b931361602e62ea4.jar:?]
	at io.github.apace100.origins.origin.OriginLayer$ConditionedOrigin.read(OriginLayer.java:381) ~[Origins-1.18.2-1.4.1.jar:?]
	at io.github.apace100.origins.origin.OriginLayer.lambda$merge$12(OriginLayer.java:159) ~[Origins-1.18.2-1.4.1.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at io.github.apace100.origins.origin.OriginLayer.merge(OriginLayer.java:159) ~[Origins-1.18.2-1.4.1.jar:?]
	at io.github.apace100.origins.origin.OriginLayers.apply(OriginLayers.java:67) ~[Origins-1.18.2-1.4.1.jar:?]
	at io.github.apace100.origins.origin.OriginLayers.method_18788(OriginLayers.java:19) ~[Origins-1.18.2-1.4.1.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_40183(class_310.java:2123) ~[client-intermediary.jar:?]
	... 28 more

Specific error in question!
